version: '3'

services:
  app:
    build:
      context: node
    container_name: app
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db
      - nginx

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '8080:80'
    networks:
      - node-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  db:
    platform: linux/x86_64
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge